### ISSUE TITLE
Client Data validation

### ISSUE THREAD

**Issue by AayushBangroo** [AayushBangroo/tourism#2]
Following data validation needs to be implemented on the Tour data coming from client side (Tour DTO):
- Tour name should have max length of 40 characters and min length of 10 characters
- Ratings average must be between 1 and 5
- difficulty can take only three values: 'easy', 'medium' and 'difficult'

**Comment by sunny64** [comment]
Pls assign this to me

**Comment by sunny64** [comment]
assigned @sunny64

**Comment by AayushBangroo** [comment]
assigned @sunny64
